# 此工作流使用未经 GitHub 认证的操作。
# 它们由第三方提供，并受
# 单独的服务条款、隐私政策和支持
# 文档。

# GitHub 建议将操作固定到提交 SHA。
# 若要获取较新版本，需要更新 SHA。
# 还可以引用标记或分支，但该操作可能会更改而不发出警告。

name: Publish Docker image
on: [push, pull_request]

jobs:
  push_to_registry:
    strategy:
      matrix:
        go-version: [1.20.x, 1.18.x]
        os: [ubuntu-latest]
    name: Push Docker image to Docker Hub
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Build dockerfile
        run: |
          fullCommit="${{ github.event.commits[0].id }}"
          docker buildx build \
            --platform=linux/amd64,linux/arm64 \
            --cache-from=type=local,src=/path/to/buildx/cache \
            --file ./Dockerfile \
            --target <build-stage> \
            --tag shed219/flowerss-bot:"${fullCommit:0:7}"

      - name: Push Docker image
        run: |
          fullCommit="${{ github.event.commits[0].id }}"
          docker buildx build \
            --platform=linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --file ./Dockerfile \
            --tag shed219/flowerss-bot:"${fullCommit:0:7}"
          docker push shed219/flowerss-bot:"${fullCommit:0:7}"
          docker tag shed219/flowerss-bot:"${fullCommit:0:7}" shed219/flowerss-bot:latest
          docker push shed219/flowerss-bot:latest
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: shed219/flowerss-bot

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
